# Profile information
name: Read Thai
title: Read Write Speak Thai - Free App to learn Thai
description: > # this means to ignore newlines until "baseurl:"
  Read write speak thai, mobile application on iOS and Android to learn to read Thai.
  Color the tone, read sentences and words.
permalink: ":title/"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://readthaiapp.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "logo.png"

# Social
facebook: readthaifunapp #Add your Facebook
twitter: joba_react #Add your Twitter
instagram: readthaifun_app #Add your Google+
github: #Add your Github

# Contact form
email: readthaifunapp@gmail.com #your-email@domain.com

analytics: UA-120912935-2
# Comments
discus-identifier: readthaiapp # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings

markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
include: [pages]

sass:
  style: compact

plugins_dir:
  - jekyll-assets
assets:
  source_maps: false # false on JEKYLL_ENV=production
  destination: "/assets"
  compression: true # true on JEKYLL_ENV=production
  gzip: true
  defaults:
    js: { integrity: true } # true on JEKYLL_ENV=production
    css: { integrity: true } # true on JEKYLL_ENV=production
    img: { integrity: true } # true on JEKYLL_ENV=production
  caching:
    path: ".jekyll-cache/assets"
    type: file # Possible values: memory, file
    enabled: true
