# Profile information
name: Read Thai
title: Read Write Speak Thai - Free App to learn Thai
description: > # this means to ignore newlines until "baseurl:"
  Read write speak thai, mobile application on iOS and Android to learn to read Thai.
  Color the tone, read sentences and words.
permalink: ":title/"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://readthaiapp.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "logo.png"

# Social
facebook: readthaifunapp #Add your Facebook
twitter: joba_react #Add your Twitter
instagram: readthaifun_app #Add your Google+
github: #Add your Github

# Contact form
email: readthaifunapp@gmail.com #your-email@domain.com

analytics: UA-120912935-2
# Comments
discus-identifier: readthaiapp # Add your Disqus identifier

# Paginate
paginate: 5
paginate_path: /page:num/

# Build settings
plugins:
  - jekyll-minifier

markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
include: [pages]

sass:
  sass_dir: _sass
  style: compressed

jekyll-minifier:
  preserve_php: true # Default: false
  remove_spaces_inside_tags: true # Default: true
  remove_multi_spaces: true # Default: true
  remove_comments: true # Default: true
  remove_intertag_spaces: true # Default: false
  remove_quotes: false # Default: false
  compress_css: true # Default: true
  compress_javascript: true # Default: true
  simple_doctype: false # Default: false
  remove_script_attributes: false # Default: false
  remove_style_attributes: false # Default: false
  remove_link_attributes: false # Default: false
  remove_form_attributes: false # Default: false
  remove_input_attributes: false # Default: false
  remove_javascript_protocol: false # Default: false
  remove_http_protocol: false # Default: false
  remove_https_protocol: false # Default: false
  preserve_line_breaks: false # Default: false
  simple_boolean_attributes: false # Default: false
  compress_js_templates: false # Default: false
