---
name: Read Thai
title: Read Write Speak Thai - Free App to learn Thai
description: 'Read write speak thai, mobile application on iOS and Android to learn
  to read Thai. Color the tone, read sentences and words.

'
permalink: ":title/"
baseurl: ''
url: https://readthaiapp.github.io
logo: logo.png
facebook: readthaifunapp
twitter: joba_react
instagram: readthaifun_app
github: 
email: readthaifunapp@gmail.com
analytics: UA-120912935-2
discus-identifier: readthaiapp
paginate: 5
paginate_path: "/page:num/"
markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
include:
- pages
sass:
  sass_dir: _sass
  style: ":compressed"
timezone: Etc/UTC
