---
name: Read Thai
title: Read Write Speak Thai - Free App to learn Thai
description: 'Read write speak thai, mobile application on iOS and Android to learn
  to read Thai. Color the tone, read sentences and words.

'
permalink: ":title/"
baseurl: ''
url: https://readthaiapp.github.io
logo: logo.png
facebook: readthaifunapp
twitter: joba_react
instagram: readthaifun_app
github: 
email: readthaifunapp@gmail.com
analytics: UA-120912935-2
discus-identifier: readthaiapp
paginate: 5
paginate_path: "/page:num/"
plugins:
- jekyll-minifier
markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
include:
- pages
sass:
  sass_dir: _sass
  style: compressed
jekyll-minifier:
  preserve_php: true
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_comments: true
  remove_intertag_spaces: true
  remove_quotes: false
  compress_css: true
  compress_javascript: true
  simple_doctype: false
  remove_script_attributes: false
  remove_style_attributes: false
  remove_link_attributes: false
  remove_form_attributes: false
  remove_input_attributes: false
  remove_javascript_protocol: false
  remove_http_protocol: false
  remove_https_protocol: false
  preserve_line_breaks: false
  simple_boolean_attributes: false
  compress_js_templates: false
timezone: Etc/UTC
