---
name: Read Thai
title: Read Write Speak Thai - Free App to learn Thai
description: 'Read write speak thai, mobile application on iOS and Android to learn
  to read Thai. Color the tone, read sentences and words.

'
permalink: ":title/"
baseurl: ''
url: https://readthaiapp.github.io
logo: logo.png
facebook: readthaifunapp
twitter: joba_react
instagram: readthaifun_app
github: 
collections:
  features:
    output: true
    permalink: "/:title"
  posts:
    output: true
    permalink: "/:title"
email: readthaifunapp@gmail.com
analytics: UA-120912935-2
discus-identifier: readthaiapp
paginate: 5
paginate_path: "/page:num/"
markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
include:
- pages
sass:
  style: compact
plugins_dir:
- jekyll-assets
assets:
  source_maps: true
  destination: "/assets"
  compression: false
  gzip: true
  defaults:
    js:
      integrity: true
    css:
      integrity: true
    img:
      integrity: true
  caching:
    path: ".jekyll-cache/assets"
    type: file
    enabled: false
timezone: Etc/UTC
