---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: directory
  path: _data
  label: Data
  create: none
  match: "**/*.{json,yaml,yml}"
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - post
upload_dir: assets/img
public_path: assets/img
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
